class AIState:
    IDLE = "Idle"
    GET_INTO_POSITION = "GetIntoPosition"
    CHASING_BALL = "ChasingBall"
    TACKLING = "Tackling"
    DEFENDING = "Defending"
    ATTACK = "Attack"
    NEUTRAL = "Neutral"
    RETREAT = "Retreat"
    FIND_DRIBBLE_LANE = "FindDribbleLane"
    DRIBBLING = "Dribbling"
    COMPlETED_DRIBBLE = "CompletedDribble"
    FIND_PASS = "FindPass"
    PASSING = "Passing"
    SHOOTING = "Shooting"
